apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aggregator
  namespace: flux-config
spec:
  targetNamespace: apps
  releaseName: aggregator
  chart:
    spec:
      chart: spring-boot-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: acr-helm
        namespace: flux-config
  interval: 15m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: turtle2005/aggregator
      tag: 1.0.0
    service:
      type: LoadBalancer
    env:
    - name: TIMEFEED_HOST
      value: http://timefeed:8080  
    replicaCount: 3