apiVersion: v1
kind: Service
metadata:
  name: timefeed
  labels:
    app: timefeed
    service: timefeed
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: timefeed
