apiVersion: v1
kind: Service
metadata:
  name: timefeed
  labels:
    app: timefeed
    service: timefeed
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: timefeed
