apiVersion: kustomize.config.k8s.io/v1beta1
Kind: Kustomization
namespace: staging
resources:
- ../base
- ./namespace.yaml
patches:
- target:
    kind: HorizontalPodAutoscaler
    name: timefeed
  path: hpa.yaml
imageTags:
- name: turtle2005/timefeed
  newTag: 1.0.1
